# Generated by Django 5.0.2 on 2024-02-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("password_hashed", models.CharField(max_length=255)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout_db.bodypart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("video_path", models.CharField(max_length=255)),
                ("muscles", models.ManyToManyField(to="workout_db.muscle")),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="ExerciseToTag", to="workout_db.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("repetitions", models.IntegerField()),
                ("weight_lbs", models.IntegerField()),
                ("rest_seconds", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workout_db.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("muscle_groups", models.ManyToManyField(to="workout_db.muscle")),
                (
                    "routines",
                    models.ManyToManyField(
                        related_name="workout_routines", to="workout_db.routine"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workout_db.tag",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        blank=True, related_name="user_workouts", to="workout_db.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="workouts",
            field=models.ManyToManyField(
                related_name="user_workouts", to="workout_db.workout"
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="workout_db.workout"
            ),
        ),
    ]
