# Generated by Django 5.0.2 on 2024-02-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="workout_routines",
                to="workout_db.workout",
            ),
        ),
    ]
