# Generated by Django 5.0.2 on 2024-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_db", "0002_alter_routine_workout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="video_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="workouts",
            field=models.ManyToManyField(
                blank=True, related_name="user_workouts", to="workout_db.workout"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="routines",
            field=models.ManyToManyField(
                blank=True, related_name="workout_routines", to="workout_db.routine"
            ),
        ),
    ]
